# Generated by Django 3.1.7 on 2021-05-15 20:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='email address')),
                ('first_name', models.CharField(blank=True, max_length=255, verbose_name='First Name')),
                ('last_name', models.CharField(blank=True, max_length=255, verbose_name='Last Name')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Characters',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('character_id', models.IntegerField()),
                ('level', models.SmallIntegerField()),
                ('ref_stroke_path', models.CharField(max_length=255)),
                ('ref_object_path', models.CharField(max_length=255)),
                ('label', models.CharField(max_length=255)),
                ('sound_path', models.CharField(max_length=255, null=True)),
                ('sequence_id', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ChildProfile',
            fields=[
                ('profile_id', models.AutoField(primary_key=True, serialize=False)),
                ('creation_date', models.DateField(auto_now_add=True, null=True)),
                ('name', models.CharField(max_length=255)),
                ('age', models.IntegerField(null=True)),
                ('gender', models.CharField(choices=[('F', 'Female'), ('M', 'Male'), ('O', 'Other')], max_length=255)),
                ('level', models.IntegerField(choices=[(0, 'Montessori'), (1, 'Nursury'), (2, 'Prep'), (3, 'other')])),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Clusters',
            fields=[
                ('cluster_id', models.AutoField(primary_key=True, serialize=False)),
                ('cluster_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='ColoringExercise',
            fields=[
                ('coloring_id', models.AutoField(primary_key=True, serialize=False)),
                ('ref_image_path', models.CharField(max_length=255)),
                ('level', models.SmallIntegerField()),
                ('sound_path', models.CharField(max_length=255, null=True)),
                ('label', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='DrawingExercise',
            fields=[
                ('drawing_id', models.AutoField(primary_key=True, serialize=False)),
                ('ref_img_path', models.CharField(max_length=255)),
                ('ref_stroke_path', models.CharField(max_length=255)),
                ('level', models.SmallIntegerField()),
                ('sound_path', models.CharField(max_length=255, null=True)),
                ('label', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Features',
            fields=[
                ('feature_id', models.AutoField(primary_key=True, serialize=False)),
                ('feature_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='ObjectWord',
            fields=[
                ('object_id', models.AutoField(primary_key=True, serialize=False)),
                ('label', models.CharField(max_length=255)),
                ('image_path', models.CharField(max_length=255)),
                ('is_object', models.BooleanField()),
                ('ref_image_path', models.CharField(max_length=255)),
                ('category', models.CharField(max_length=255)),
                ('sound_path', models.CharField(max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='WordsUrdu',
            fields=[
                ('word_id', models.AutoField(primary_key=True, serialize=False)),
                ('ref_stroke_path', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='History',
            fields=[
                ('attempt_id', models.AutoField(primary_key=True, serialize=False)),
                ('stroke_path', models.CharField(max_length=255)),
                ('time_taken', models.IntegerField()),
                ('stroke_score', models.FloatField(blank=True, null=True)),
                ('similarity_score', models.FloatField(blank=True, null=True)),
                ('datetime_attempt', models.DateTimeField()),
                ('is_completed', models.BooleanField()),
                ('character_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='user.characters')),
                ('coloring_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='user.coloringexercise')),
                ('drawing_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='user.drawingexercise')),
                ('object_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='user.objectword')),
                ('profile_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.childprofile')),
                ('word_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.wordsurdu')),
            ],
        ),
        migrations.CreateModel(
            name='Dashoard',
            fields=[
                ('dashboard_id', models.AutoField(primary_key=True, serialize=False)),
                ('time_path', models.CharField(max_length=255)),
                ('score_path', models.CharField(max_length=255)),
                ('completion_path', models.CharField(max_length=255)),
                ('profile_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.childprofile')),
            ],
        ),
        migrations.CreateModel(
            name='ClusterFeature',
            fields=[
                ('cluster_feature_id', models.AutoField(primary_key=True, serialize=False)),
                ('cluster_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.clusters')),
                ('feature_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.features')),
            ],
        ),
        migrations.AddField(
            model_name='characters',
            name='cluster_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='user.clusters'),
        ),
        migrations.CreateModel(
            name='AttemptFeatures',
            fields=[
                ('attempt_feature_id', models.AutoField(primary_key=True, serialize=False)),
                ('score', models.FloatField()),
                ('attempt_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.history')),
                ('feature_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.features')),
            ],
        ),
    ]
