# Generated by Django 3.1.7 on 2021-05-15 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='wordsurdu',
            name='word_label',
            field=models.CharField(default=6, max_length=255),
            preserve_default=False,
        ),
    ]
