# Generated by Django 3.1.7 on 2021-05-06 21:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Clusters',
            fields=[
                ('cluster_id', models.AutoField(primary_key=True, serialize=False)),
                ('cluster_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Features',
            fields=[
                ('feature_id', models.AutoField(primary_key=True, serialize=False)),
                ('feature_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Dashoard',
            fields=[
                ('dashboard_id', models.AutoField(primary_key=True, serialize=False)),
                ('time_path', models.CharField(max_length=255)),
                ('score_path', models.CharField(max_length=255)),
                ('completion_path', models.CharField(max_length=255)),
                ('profile_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.childprofile')),
            ],
        ),
        migrations.CreateModel(
            name='ClusterFeature',
            fields=[
                ('cluster_feature_id', models.AutoField(primary_key=True, serialize=False)),
                ('cluster_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.clusters')),
                ('feature_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.features')),
            ],
        ),
        migrations.CreateModel(
            name='AttemptFeatures',
            fields=[
                ('attempt_feature_id', models.AutoField(primary_key=True, serialize=False)),
                ('score', models.FloatField()),
                ('attempt_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.history')),
                ('feature_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.features')),
            ],
        ),
        migrations.AddField(
            model_name='characters',
            name='cluster_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='user.clusters'),
        ),
    ]
