# Generated by Django 3.1.7 on 2021-05-06 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20210507_0208'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='childprofile',
            name='dob',
        ),
        migrations.AddField(
            model_name='childprofile',
            name='age',
            field=models.IntegerField(null=True),
        ),
    ]
