# Generated by Django 3.1.7 on 2021-05-15 21:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_wordsurdu_word_label'),
    ]

    operations = [
        migrations.AlterField(
            model_name='history',
            name='word_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user.wordsurdu'),
        ),
    ]
