# Generated by Django 3.1.3 on 2020-11-25 21:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20201124_1946'),
    ]

    operations = [
        migrations.CreateModel(
            name='childProfile',
            fields=[
                ('profileid', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('dob', models.DateField(verbose_name='Date of Birth')),
                ('gender', models.CharField(choices=[('F', 'Female'), ('M', 'Male'), ('O', 'Other')], max_length=255)),
                ('level', models.IntegerField(choices=[(0, 'Montisorry'), (1, 'Nursury'), (2, 'Prep'), (3, 'other')])),
                ('userid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
