# Generated by Django 3.1.3 on 2020-12-05 16:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_childprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Characters',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('character_id', models.IntegerField()),
                ('level', models.SmallIntegerField()),
                ('ref_stroke_path', models.CharField(max_length=255)),
                ('ref_object_path', models.CharField(max_length=255)),
                ('label', models.CharField(max_length=255)),
                ('sound_path', models.CharField(max_length=255, null=True)),
                ('sequence_id', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ColoringExercise',
            fields=[
                ('coloring_id', models.AutoField(primary_key=True, serialize=False)),
                ('ref_image_path', models.CharField(max_length=255)),
                ('level', models.SmallIntegerField()),
                ('sound_path', models.CharField(max_length=255, null=True)),
                ('label', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='DrawingExercise',
            fields=[
                ('drawing_id', models.AutoField(primary_key=True, serialize=False)),
                ('ref_img_path', models.CharField(max_length=255)),
                ('ref_stroke_path', models.CharField(max_length=255)),
                ('level', models.SmallIntegerField()),
                ('sound_path', models.CharField(max_length=255, null=True)),
                ('label', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='ObjectWord',
            fields=[
                ('object_id', models.AutoField(primary_key=True, serialize=False)),
                ('label', models.CharField(max_length=255)),
                ('image_path', models.CharField(max_length=255)),
                ('is_object', models.BooleanField()),
                ('ref_image_path', models.CharField(max_length=255)),
                ('category', models.CharField(max_length=255)),
                ('sound_path', models.CharField(max_length=255, null=True)),
            ],
        ),
        migrations.RenameField(
            model_name='childprofile',
            old_name='profileid',
            new_name='profile_id',
        ),
        migrations.RenameField(
            model_name='childprofile',
            old_name='userid',
            new_name='user_id',
        ),
        migrations.AddField(
            model_name='childprofile',
            name='creation_date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('session_id', models.AutoField(primary_key=True, serialize=False)),
                ('time_start', models.DateTimeField(auto_now_add=True, null=True)),
                ('time_end', models.DateTimeField(blank=True, null=True)),
                ('token', models.CharField(max_length=255)),
                ('profile_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.childprofile')),
            ],
        ),
        migrations.CreateModel(
            name='History',
            fields=[
                ('attempt_id', models.AutoField(primary_key=True, serialize=False)),
                ('stroke_path', models.CharField(max_length=255)),
                ('time_taken', models.IntegerField()),
                ('stroke_score', models.FloatField(blank=True, null=True)),
                ('similarity_score', models.FloatField(blank=True, null=True)),
                ('datetime_attempt', models.DateTimeField()),
                ('is_completed', models.BooleanField()),
                ('character_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='user.characters')),
                ('coloring_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='user.coloringexercise')),
                ('drawing_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='user.drawingexercise')),
                ('object_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='user.objectword')),
                ('session_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.session')),
            ],
        ),
    ]
