# Generated by Django 3.1.5 on 2021-04-26 20:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_clustercharacter_clusterfeature_clusters_features'),
    ]

    operations = [
        migrations.AddField(
            model_name='characters',
            name='cluster_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='user.clusters'),
        ),
        migrations.DeleteModel(
            name='ClusterCharacter',
        ),
    ]
