# Generated by Django 3.1.5 on 2021-04-27 18:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_auto_20210427_0127'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttemptFeatures',
            fields=[
                ('attempt_feature_id', models.AutoField(primary_key=True, serialize=False)),
                ('score', models.IntegerField()),
                ('attempt_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.history')),
                ('feature_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.features')),
            ],
        ),
    ]
