# Generated by Django 3.1.5 on 2021-05-04 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_attemptfeatures'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attemptfeatures',
            name='score',
            field=models.FloatField(),
        ),
    ]
