# Generated by Django 3.1.5 on 2021-05-05 20:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_auto_20210505_0144'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dashoard',
            fields=[
                ('dashboard_id', models.AutoField(primary_key=True, serialize=False)),
                ('time_path', models.CharField(max_length=255)),
                ('score_path', models.CharField(max_length=255)),
                ('completion_path', models.CharField(max_length=255)),
                ('profile_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.childprofile')),
            ],
        ),
    ]
